fonts:
  - Roboto
  - Open+Sans
  - Space+Mono
  - Lato
  - Montserrat
  - Oswald
  - Raleway
  - Merriweather
  - Inconsolata
  - Allura
  - Sigmar+One
  - Gloria+Hallelujah
  - Montez
  - Lobster
  - Josefin+Sans
  - Shadows+Into+Light
  - Pacifico
  - Amatic+SC:700
  - Orbitron:400,900
  - Rokkitt
  - Righteous
  - Dancing+Script:700
  - Bangers
  - Chewy
  - Sigmar+One
  - Architects+Daughter
  - Abril+Fatface
  - Covered+By+Your+Grace
  - Kaushan+Script
  - Gloria+Hallelujah
  - Satisfy
  - Lobster+Two:700
  - Comfortaa:700
  - Cinzel
  - Courgette
