error_settings:
  display_error_details: true
  log_error_details: true
  log_errors: true
logger:
  name: slim-app
  level: debug
  file_name: app.log
session:
  session_name: hexbatch_flow_session
  flash_key : hexbatch_flow_flash
twig:
    cache: false
    strict_variables: true
    debug: true
project:
    parent_directory: /var/www/flow_projects
