error_settings:
  display_error_details: true
  log_error_details: true
  log_errors: true
logger:
  name: slim-app
  level: debug
  file_name: app.log
session:
  session_name: hexbatch_flow_session
  flash_key : hexbatch_flow_flash
twig:
  cache: true
  strict_variables: true
  debug: true,
  auto_reload: true
project:
  parent_directory: /var/www/flow_projects
git:
  supported_hosts:
    - github.com
    - bitbucket.org
    - gitlab.com
program:
    version: 0.6.2-alpha
    version_link: "https://github.com/hexbatch/hexbatch-core-flow/pull/6"
    version_description_short: "BB Code is now a first class citizen"
    timezone: 'America/Chicago'
